const LABEL_BABYSITTER = 'BABYSITTER';

const LABEL_CHATS = 'CHATS';

const LABEL_DESCRIPTION = 'DESCRIPTION';

const LABEL_DELETE = 'DELETE';

const LABEL_EDIT = 'EDIT';

const LABEL_EMAIL = 'EMAIL';

const LABEL_EMPTY_PROFILES = 'NO PROFILES';

const LABEL_FIRST_NAME = 'FIRST NAME';

const LABEL_JOBS = 'JOBS';

const LABEL_LAST_NAME = 'LAST NAME';

const LABEL_LOG_IN = 'LOG IN';

const LABEL_NAME = 'NAME';

const LABEL_NUMBER = 'NUMBER';

const LABEL_PARENT = 'PARENT';

const LABEL_PASSWORD = 'PASSWORD';

const LABEL_REGISTER = 'REGISTER';

const LABEL_RELOAD = 'RELOAD';

const LABEL_REQUESTS = 'REQUESTS';

const LABEL_SCHEDULE = 'SCHEDULE';

const LABEL_SCHEDULE_START = 'SCHEDULE START';

const LABEL_SCHEDULE_END = 'SCHEDULE END';

const LABEL_SUBMIT = 'SUBMIT';

const LABEL_TITLE = 'TITLE';

const LABEL_TYPE = 'TYPE';

const LABEL_USERNAME = 'USERNAME';

const MESSAGE_PROFILES_LOAD_FAIL = 'FAILED TO LOAD PROFILES!';

const MESSAGE_APPLY_FAIL = 'FAILED TO APPLY FOR JOB!';

const MESSAGE_APPLY_SUCCESS = 'SUCCESSFULLY APPLIED TO JOB!';

const MESSAGE_APPLY_TRY = 'TRYING TO APPLY FOR JOB...';

const MESSAGE_JOBS_FAIL = 'FAILED TO SAVE JOB!';

const MESSAGE_JOBS_SUCCESS = 'JOB SUCCESSFULLY SAVED!';

const MESSAGE_JOBS_TRY = 'TRYING TO SAVE JOB...';

const MESSAGE_LOG_IN_FAIL = 'FAILED TO LOG IN!';

const MESSAGE_LOG_IN_SUCCESS = 'LOG-IN SUCCESSFUL!';

const MESSAGE_LOG_IN_TRY = 'TRYING TO LOG IN...';

const MESSAGE_REGISTRATION_FAIL = 'FAILED TO REGISTER NEW USER!';

const MESSAGE_REGISTRATION_SUCCESS = 'SUCCESSFULLY REGISTERED USER!';

const MESSAGE_REGISTRATION_TRY = 'TRYING TO REGISTER NEW USER...';

const SEND_MESSAGE_FAIL = 'FAILED TO SEND MESSAGE!';

const SEND_MESSAGE_SUCCESS = 'MESSAGE SUCCESSFULLY SENT!';

const SEND_MESSAGE_TRY = 'TRYING TO SEND MESSAGE...';

const TITLE_APP = 'iCare';

const TITLE_JOBS_ALL = 'All Jobs';

const TITLE_JOBS_NEW = 'New Job';

const TITLE_JOBS_OPEN = 'Open Jobs';

const TITLE_LOG_IN = 'Log In';

const TITLE_MY_JOBS = 'My Jobs';

const TITLE_REGISTER = 'Register';

const TITLE_WELCOME = "Welcome to our website we offer blab la bla"

const WARNING_NOT_LOGGED = 'YOU ARE NOT LOGGED IN!';


//updated 

const LABEL_SITTERS = 'SITTERS';
const LABEL_WATCHLIST = 'WATCH LIST';
const LABEL_LOGOUT = 'LOG OUT'
const LABEL_FAMILIES = 'FAMILIES';

const TITLE_ALL_SITTERS = 'All Sitters'; //all sitters page
const LABEL_PRICE_RANGE = 'Price Range';
const LABEL_AGE_RANGE = 'Age Range';
const LABEL_GENDER = 'Gender';
const LABEL_CHILD_CARE = 'Child Care';
const LABEL_SCHOOL_HELP = 'School Help';
const LABEL_AGE = 'Age';
const LABEL_PRICE = 'Price';
const LABEL_SKILLS = 'Skills';
const LABEL_PROFILE = 'Profile';

//sitter profile
const TITLE_SITTER_REVIEWS = 'Sitter Reviews';
const TITLE_SITTER_JOBS = 'Sitter Jobs';

//job detail
const TITLE_JOB_COMMENTS = 'Job Comments';

//registration
const LABEL_LOC = 'Location';
const LABEL_SHORT_INFO = 'Short Information';
const LABEL_EDUCATION = 'Education';
const LABEL_EXP_YEARS = 'Experienced Years';
const LABEL_NUM_OF_CHILDREN = 'Number of Children';


//parent profile
const TITLE_PARENT_REVIEWS = 'Parent Reviews';
const TITLE_PARENT_JOBS = 'Parent Jobs';


const TITLE_ALL_PARENTS = 'All Parents'; //all parents pages

//request page
const TITLE_APPLIED_JOBS = 'All My Applied Jobs';
const TITLE_POSTED_JOBS = 'All My Posted Jobs';


const StringsEnglish = Object.freeze({
    LABEL_BABYSITTER,
    LABEL_CHATS,
    LABEL_DESCRIPTION,
    LABEL_DELETE,
    LABEL_EDIT,
    LABEL_EMAIL,
    LABEL_EMPTY_PROFILES,
    LABEL_FIRST_NAME,
    LABEL_JOBS,
    LABEL_LAST_NAME,
    LABEL_LOG_IN,
    LABEL_NAME,
    LABEL_NUMBER,
    LABEL_PARENT,
    LABEL_PASSWORD,
    LABEL_REGISTER,
    LABEL_RELOAD,
    LABEL_REQUESTS,
    LABEL_SCHEDULE,
    LABEL_SCHEDULE_START,
    LABEL_SCHEDULE_END,
    LABEL_SUBMIT,
    LABEL_TITLE,
    LABEL_TYPE,
    LABEL_USERNAME,
    MESSAGE_APPLY_FAIL,
    MESSAGE_APPLY_SUCCESS,
    MESSAGE_APPLY_TRY,
    MESSAGE_JOBS_FAIL,
    MESSAGE_JOBS_SUCCESS,
    MESSAGE_JOBS_TRY,
    MESSAGE_LOG_IN_FAIL,
    MESSAGE_LOG_IN_SUCCESS,
    MESSAGE_LOG_IN_TRY,
    MESSAGE_PROFILES_LOAD_FAIL,
    MESSAGE_REGISTRATION_FAIL,
    MESSAGE_REGISTRATION_SUCCESS,
    MESSAGE_REGISTRATION_TRY,
    SEND_MESSAGE_FAIL,
    SEND_MESSAGE_SUCCESS,
    SEND_MESSAGE_TRY,
    TITLE_APP,
    TITLE_JOBS_ALL,
    TITLE_JOBS_NEW,
    TITLE_JOBS_OPEN,
    TITLE_LOG_IN,
    TITLE_MY_JOBS,
    TITLE_REGISTER,
    WARNING_NOT_LOGGED,

    LABEL_SITTERS,//updated
    LABEL_WATCHLIST,
    LABEL_FAMILIES,
    LABEL_LOGOUT,

    TITLE_ALL_SITTERS, //all sitters page
    LABEL_PRICE_RANGE,
    LABEL_AGE_RANGE, 
    LABEL_GENDER,
    LABEL_CHILD_CARE,
    LABEL_SCHOOL_HELP,
    LABEL_AGE,
    LABEL_PRICE,
    LABEL_SKILLS,
    LABEL_PROFILE,

    LABEL_LOC,
    LABEL_SHORT_INFO,
    LABEL_EDUCATION,
    LABEL_EXP_YEARS,
    LABEL_NUM_OF_CHILDREN,

    TITLE_SITTER_REVIEWS, //sitter profile page
    TITLE_SITTER_JOBS, 

    TITLE_JOB_COMMENTS, //job detail

    TITLE_ALL_PARENTS, //parents page

    TITLE_PARENT_REVIEWS, //sitter profile page
    TITLE_PARENT_JOBS,     

    TITLE_POSTED_JOBS, //request page
    TITLE_APPLIED_JOBS,

    TITLE_WELCOME
});

export default StringsEnglish;
