# Generated by Django 3.2.5 on 2022-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0005_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('babysitter_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('contents', models.TextField()),
            ],
        ),
    ]
