# Generated by Django 3.2.5 on 2022-06-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0006_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='parent_id',
        ),
    ]
