# Generated by Django 4.0.6 on 2022-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0009_registration_age_registration_exp_years_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='full_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='registration',
            name='num_of_children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
