# Generated by Django 4.0.6 on 2022-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
