# Generated by Django 4.0.6 on 2022-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0013_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('description', models.TextField()),
                ('enabled', models.BooleanField()),
                ('post_time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('description', models.TextField()),
                ('enabled', models.BooleanField()),
                ('post_time', models.BigIntegerField()),
            ],
        ),
    ]
