# Generated by Django 4.0.6 on 2022-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0014_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('post_time', models.BigIntegerField()),
            ],
        ),
    ]
