# Generated by Django 4.0.6 on 2022-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0015_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='education',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
