# Generated by Django 4.0.6 on 2022-07-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0016_registration_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('post_time', models.BigIntegerField()),
            ],
        ),
    ]
