# Generated by Django 4.0.6 on 2022-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0017_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
