# Generated by Django 4.0.6 on 2022-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0018_job_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_type',
            field=models.TextField(),
        ),
    ]
