# Generated by Django 4.0.6 on 2022-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0020_rename_babysitter_id_application_from_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_b',
            field=models.TextField(),
        ),
    ]
