const ERROR_NOT_AUTHORIZED = 'NOT AUTHORIZED TO DO THIS OPERATION';

const ERROR_SERVER_TIMEOUT = 'THE SERVER TOOK TOO LONG TO RESPOND';

const ERROR_UNKNOWN = 'AN UNEXPECTED ERROR HAPPENED';

const ErrorsEnglish = Object.freeze({
    ERROR_NOT_AUTHORIZED,
    ERROR_SERVER_TIMEOUT,
    ERROR_UNKNOWN,
});

export default ErrorsEnglish;